baseURL = 'https://ddr2000.github.io/'
languageCode = 'en-us'
theme = 'paper'
disableThemeToggle = true
[params.profileMode]
title = 'Dilir D Rafid'
imageUrl = "photo.jpeg"
imageTitle = "Dilir"
imageWidth = 160
imageHeight = 160
enabled = true


  [[params.profileMode.buttons]]
  name = "Posts"
  url = "/posts"

  [[params.profileMode.buttons]]
  name = "LinkedIn"
  url = 'https://www.linkedin.com/in/dilir-diyan-09977716b/'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
